# Testing Machine Learning & General `python` Tools

This is a test notebook to see the capabilities of `pandas`, `numpy`, `matplotlib`, and largely the functionality of `jupyter notebook` in the grand scheme of data science and data analysis.


## Dependencies 

*Here are some common ML packages - `pandas`, `numpy`, and `matplotlib`*
Small note on installing these if you haven't already. I was running into an issue in running 

` $ pip install pandas `

and realized that in order to install python3 packages (which everyone should, really 🙂), you need to use the following:

``` 
    $ pip3 install pandas 
    $ pip3 install numpy  
    $ pip3 install matplotlib 
```

In [21]:
import pandas as pd
import numpy as np
import matplotlib as mp

filename = "cars.csv"

In [12]:
# Testing shift enter functionality with classic liftoff problem
for i in range(10, 0, -1):
    print(i)
print("Liftoff!")

10
9
8
7
6
5
4
3
2
1
Liftoff!


In [22]:
with open(filename, 'r') as f:
    for line in f:
        line_data = line.split(";")
        print(line_data[0])

Car
STRING
Chevrolet Chevelle Malibu
Buick Skylark 320
Plymouth Satellite
AMC Rebel SST
Ford Torino
Ford Galaxie 500
Chevrolet Impala
Plymouth Fury iii
Pontiac Catalina
AMC Ambassador DPL
Citroen DS-21 Pallas
Chevrolet Chevelle Concours (sw)
Ford Torino (sw)
Plymouth Satellite (sw)
AMC Rebel SST (sw)
Dodge Challenger SE
Plymouth 'Cuda 340
Ford Mustang Boss 302
Chevrolet Monte Carlo
Buick Estate Wagon (sw)
Toyota Corolla Mark ii
Plymouth Duster
AMC Hornet
Ford Maverick
Datsun PL510
Volkswagen 1131 Deluxe Sedan
Peugeot 504
Audi 100 LS
Saab 99e
BMW 2002
AMC Gremlin
Ford F250
Chevy C20
Dodge D200
Hi 1200D
Datsun PL510
Chevrolet Vega 2300
Toyota Corolla
Ford Pinto
Volkswagen Super Beetle 117
AMC Gremlin
Plymouth Satellite Custom
Chevrolet Chevelle Malibu
Ford Torino 500
AMC Matador
Chevrolet Impala
Pontiac Catalina Brougham
Ford Galaxie 500
Plymouth Fury iii
Dodge Monaco (sw)
Ford Country Squire (sw)
Pontiac Safari (sw)
AMC Hornet Sportabout (sw)
Chevrolet Vega (sw)
Pontiac Firebird
Ford Mu

In [28]:
with open(filename, 'r') as f:
    result = {}
    for line in f:
        line_data = line.split(";")
        car = line_data[0]
        car_metadata = car.split()
        car_name = car_metadata[0] 
        if car_name not in result:
            result[car_name] = ["".join(car_metadata[1:])]
        result[car_name].append("".join(car_metadata[1:]))
print(sorted(result.keys()))

['AMC', 'Audi', 'BMW', 'Buick', 'Cadillac', 'Capri', 'Car', 'Chevrolet', 'Chevrolete', 'Chevy', 'Chrysler', 'Citroen', 'Datsun', 'Dodge', 'Fiat', 'Ford', 'Hi', 'Honda', 'Mazda', 'Mercedes', 'Mercedes-Benz', 'Mercury', 'Nissan', 'Oldsmobile', 'Opel', 'Peugeot', 'Plymouth', 'Pontiac', 'Renault', 'STRING', 'Saab', 'Subaru', 'Toyota', 'Triumph', 'Volkswagen', 'Volvo']


# Testing `urllib`

In [50]:
import urllib
from urllib.parse import urlparse

parse1 = urlparse('https://www.nkishnani.com')
parse2 = urlparse('https://www.careervillage.org')
parse3 = urlparse('https://www.google.com:80')
parse1, parse2, parse3

with urllib.request.urlopen('https://www.isitchristmas.com') as response:
    html = response.read()
    print(html)


b'<!--\n\n  Built by Eric Mill. twitter.com/konklone\n  With huge thanks to Brandon Jones. twitter.com/btj\n\n  Bug reports and stuff:\n    github.com/isitchristmas/web/issues\n\n  Open the developer console.\n\n-->\n\n<!doctype html>\n<html lang="en">\n<head>\n  <link rel="authors" href="/humans.txt" />\n\n  <meta charset="utf-8" />\n  <title>Is it Christmas?</title>\n\n  <link rel="shortcut icon" href="/icons/large.png" />\n\n  <link rel="alternate" title="Is It Christmas?" href="/rss.xml" type="application/rss+xml" />\n  <link rel="alternate" title="Is It Christmas? (Christmas only)" href="/rss.xml?only=yes" type="application/rss+xml" />\n\n  <meta name="twitter:site" content="@konklone">\n  <meta name="twitter:creator" content="@konklone">\n  <meta property="og:site_name" content="Is It Christmas?" />\n  <meta property="og:type" content="website" />\n  <meta property="og:url" content="https://isitchristmas.com" />\n\n  <meta property="og:title" content="Is It Christmas?" />\n\n  <m

# Learning `numpy` 

[Cited from TutorialsPoint](https://www.tutorialspoint.com/numpy/numpy_ndarray_object.htm)
> The most important object defined in NumPy is an N-dimensional array type called ndarray. It describes the collection of items of the same type. Items in the collection can be accessed using a zero-based index.

In [64]:
first_array = np.array([[1, 2, 3], [4, 5, 6]])
first_array.shape = (3, 2) # reformats first_array to be a 3 x 2 matrix (started as 2 x 3)
print("Here's the first shaped array: ")
print(first_array)
first_array.reshape(3, 2)
print("Here's the second reshaped array: ")
print(first_array)
print("These should be the same!")

Here's the first shaped array: 
[[1 2]
 [3 4]
 [5 6]]
Here's the second reshaped array: 
[[1 2]
 [3 4]
 [5 6]]
These should be the same!


In [72]:
range_list = range(10)
print(range_list)
range_nparray = np.arange(10)
print(range_nparray)
range_nparray[0]

range(0, 10)
[0 1 2 3 4 5 6 7 8 9]


0